# æ­¤é…ç½®æ–‡ä»¶ä¸ºç³»ç»Ÿä½¿ç”¨ï¼Œè¯·å‹¿ä¿®æ”¹ï¼Œå¦åˆ™å¯èƒ½æ— æ³•æ­£å¸¸ä½¿ç”¨
# ç”¨æˆ·é…ç½®å·²ç§»åŠ¨è‡³ Yz/config/DF-Plugin.yaml

CodeUpdate:
  AutoTips: |-
    è‡ªåŠ¨æ£€æŸ¥ä»“åº“æ›´æ–°å¼€å…³
  Auto: false
  
  AutoBranchTips: |-
    æ˜¯å¦è‡ªåŠ¨ç»™æœªé…ç½®åˆ†æ”¯çš„ä»“åº“æ·»åŠ é»˜è®¤åˆ†æ”¯
  AutoBranch: true

  CronTips: |-
    ä»“åº“æ›´æ–°æ£€æŸ¥Cronè¡¨è¾¾å¼
    Github/Gitee Api æœªè®¤è¯ç”¨æˆ·æ¯å°æ—¶é™åˆ¶60 (ipé™åˆ¶), è®¤è¯ç”¨æˆ·æ¯å°æ—¶é™åˆ¶5000æ¬¡ (è´¦å·é™åˆ¶)
  Cron: "0 */30 * * * *"

  RepoTips: |-
    GitApié…ç½®
      provider: ä»“åº“æä¾›å•†ï¼Œå”¯ä¸€æ ‡è¯†ç¬¦
      token: è®¤è¯Token
      ApiUrl: Apiåœ°å€
  repos:
  - provider: "GitHub"
    token: ""
    ApiUrl: "https://api.github.com/repos"
    icon: "GitHub"
    tips: Githubä¸ªäººToken è·å–åœ°å€ https://github.com/settings/tokens
  - provider: "Gitee"
    token: ""
    ApiUrl: "https://gitee.com/api/v5/repos"
    icon: "Gitee"
    tips: Giteeä¸ªäººToken è·å–åœ°å€ https://gitee.com/profile/personal_access_tokens
  - provider: "Gitcode"
    token: ""
    ApiUrl: "https://gitcode.com/api/v5/repos"
    icon: "Gitcode"
    tips: Gitcodeä¸ªäººToken è·å–åœ°å€ https://gitcode.com/setting/token-classic

  ListTips: |-
    æ¨é€é…ç½®
    Group: æ¨é€çš„ç¾¤èŠåˆ—è¡¨
    QQ: æ¨é€çš„QQåˆ—è¡¨
    AutoPath: æ˜¯å¦è‡ªåŠ¨è·å–å·²å®‰è£…çš„æ’ä»¶åœ°å€å¹¶ç›‘å¬
    Exclude: æ’é™¤çš„ä»“åº“è·¯å¾„(ç”¨äºå¿½ç•¥ä¸€äº›ä¸å¸Œæœ›è¢«ç›‘å¬çš„æ’ä»¶)
    repos: 
        provider: ä»“åº“æä¾›å•†ï¼Œå”¯ä¸€æ ‡è¯†ç¬¦
        repo: ä»“åº“å
        branch: åˆ†æ”¯å (commitæ—¶æœ‰æ•ˆ ä¸ºç©ºè‡ªåŠ¨è·å–)
        type: commit æˆ– release
        icon: å›¾æ ‡
    note: å¤‡æ³¨
  List: []

Poke: 
  chuoTips: |-
    æˆ³ä¸€æˆ³å¼€å…³
  chuo: true

  modeTips: |-
    æˆ³ä¸€æˆ³æ¨¡å¼
    image: è¿”å›å›¾ç‰‡æ¶ˆæ¯
    text: è¿”å›æ–‡æœ¬æ¶ˆæ¯
    random: éšæœºè¿”å›æ–‡æœ¬æˆ–å›¾ç‰‡
    mix: åŒæ—¶æ˜¾ç¤ºå›¾ç‰‡+æ–‡å­—
  mode: image

  imageTypeTips: |-
    æˆ³ä¸€æˆ³å›¾ç‰‡è®¾ç½®
    1: æŸ´éƒ¡
    2: ä¸›é›¨
    3: è¯—æ­Œå‰§ 
    4: æŸšå­å¨ 
    5: å°å—æ¢
    6: å°é²¨é±¼å¤æ‹‰
    7: ç”˜åŸçŒ«çŒ«
    8: é¾™å›¾
    9: æ»¡ç©—
    10: çŒ«çŒ«è™«
    11: çº³è¥¿å¦²
    12: å¿ƒæµ·
    13: fufu
    14: ATRI
    15: ç»«åœ°å®å®
    16: æ°¸é›å¡”è²
    17: miku
    18: ç‰¹è•¾è¥¿å¨…
    19: doro
    20: ç±³å¡”
    0: è‡ªå®šä¹‰å›¾ç‰‡ (è‡ªè¡Œåœ¨resources/poke/defaultä¸­æ·»åŠ )
    all: éšæœºç±»å‹
  imageType: 1

  imageBlackTips: |-
    æˆ³ä¸€æˆ³éšæœºå›¾ç‰‡é»‘åå•
  imageBlack:
    - default

  textModeTips: |-
    æˆ³ä¸€æˆ³æ–‡å­—è®¾ç½®
    hitokoto: ä¸€è¨€
    list: è‡ªå®šä¹‰æ–‡æœ¬
  textMode: hitokoto

  textListTips: |-
    æˆ³ä¸€æˆ³æ–‡å­—åˆ—è¡¨
    æ­¤åˆ—è¡¨çš„æ–‡å­—å°†è¢«éšæœº
  textList:
    - ä½ å¹²å˜›å“å‘¦


other:
  ysTips: |-
    åŸç¥å…³é”®è¯å‘å›¾
  ys: true

Picture:
  openTips: |-
    éšæœºå›¾ç‰‡å¼€å…³
  open: true

  DirectTips: |-
    æ˜¯å¦å»é™¤ #æ¥å¼ /éšæœº å‰ç¼€
  Direct: false

sendMaster:
  openTips: |-
    è”ç³»ä¸»äººå¼€å…³
  open: true

  cdTips: |-
    è”ç³»ä¸»äººCD å•ä½: ç§’ å¡«0å…³é—­cd
  cd: 30

  MasterTips: |-
    æ˜¯å¦å‘é€å…¨éƒ¨ä¸»äºº 0: ä»…å‘é€é¦–ä¸ªä¸»äºº 1: å‘é€å…¨éƒ¨ä¸»äºº 
    å¡«ä¸»äººè´¦å·å¯ä»¥æŒ‡å®šå‘é€æŸä¸ªä¸»äºº
  Master: 0

  BotIdTips: |-
    æŒ‡å®šæŸä¸ªBotå‘é€ ä¸º0æ—¶ä¸ºè§¦å‘Bot
  BotId: 0

  sendAvatarTips: |-
    æ˜¯å¦å‘é€è§¦å‘è€…çš„å¤´åƒï¼ˆå¾®ä¿¡è¯·å…³é—­æ­¤é¡¹ï¼‰
  sendAvatar: true

  replyQQTips: |-
    æ˜¯å¦å›å¤ä¸»äººQQå·
  replyQQ: true

  banWordsTips: |-
    è¿ç¦è¯ï¼Œå½“æ¶ˆæ¯åŒ…å«ä¸‹åˆ—å†…å®¹å°†ä¸ä¼šå‘é€ç»™ä¸»äºº
  banWords:
    - åƒåœ¾
    - ä½ å¦ˆ
    - nm
    - æœˆå—
    - ğŸˆ·ï¸å—
    - ğŸˆ·å—
    - çº¦å—

  banUserTips: |-
    ç¦ç”¨çš„ç”¨æˆ·ï¼Œä¸å…è®¸è¯¥ç”¨æˆ·è”ç³»ä¸»äºº
  banUser:
    - 10086

  banGroupTips: |-
    ç¦ç”¨çš„ç¾¤èŠï¼Œä¸å…è®¸é€šè¿‡è¯¥ç¾¤è”ç³»ä¸»äºº
  banGroup:
    - 114514

summary:
  sumTips: |-
    å›¾ç‰‡å¤–æ˜¾å¼€å…³
  sum: false

  typeTips: |-
    å¤–æ˜¾æ¨¡å¼ (1: è‡ªå®šä¹‰å¤–æ˜¾ 2:  ä¸€è¨€æ¥å£ 3: åˆ—è¡¨éšæœº)
  type: 2

  textTips: |-
    è‡ªå®šä¹‰å¤–æ˜¾
  text: "Cialloï½(âˆ ãƒ»Ï‰< )âŒ’â˜†"

  listTips: |-
    è‡ªå®šä¹‰å¤–æ˜¾éšæœºåˆ—è¡¨
  list:
    - ä½ å¹²å˜›~
    - æˆ‘å–œæ¬¢ä½ 

  apiTips: |-
    ä¸€è¨€æ¥å£
  api: "https://v1.hitokoto.cn/?encode=text"

proxy:
  openTips: |-
    æ˜¯å¦ä»£ç†å¤§éƒ¨åˆ†è¯·æ±‚
  open: false

  urlTips: |-
    ä»£ç†åœ°å€
  url: "http://127.0.0.1:7890"